spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.security.oauth2.client.registration.google.client-id=teste
spring.security.oauth2.client.registration.google.client-secret=teste
spring.security.oauth2.client.registration.google.scope[0]=openid
spring.security.oauth2.client.registration.google.scope[1]=profile
spring.security.oauth2.client.registration.google.scope[2]=email


