spring.application.name=OrcaFlow
spring.datasource.url=jdbc:postgresql://localhost:5432/orca_db?CreateDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

