spring.application.name=OrcaFlow
spring.datasource.url=jdbc:postgresql://${URL_DB}:5432/orca_db?CreateDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

